### ISSUE TITLE
no thread output for avsforum

### ISSUE THREAD

**Issue by mitchcapper** [TUVIMEN/xenforo-scraper#7]
for example:
```
./xenforo --no-users --no-reactions --thread "https://www.avsforum.com/threads/what-should-i-replace-my-marantz-sr6011-avr-with.3272103/" && cat 327*
```
```js
{"link":"https://www.avsforum.com/threads/what-should-i-replace-my-marantz-sr6011-avr-with.3272103/","id":"3272103","title":"","user_id":"","user":"","date":"","path":"","tags":[],"poll":{"title":"","answers":[]},"posts":[]}
```

**Comment by mitchcapper** [comment]
Tried on two of the provided sample sites as well:
`./xenforo --thread "https://www.urban75.net/forums/threads/they-all-possibly-went-on-holiday-at-same-time-because-they-all-knew-and-wanted-others-to-cop-for-the-blame.375866/"`

`./xenforo --thread "https://forums.freddyshouse.com/threads/new-freddyshouse-guides-site-new.242564/"
https://forums.freddyshouse.com/threads/new-freddyshouse-guides-site-new.242564/"`

--old also didn't seem to fix

**Comment by TUVIMEN** [comment]
All of the examples given by you seem to work for me, maybe you should update xenforo or hgrep. Also looking by the output it might be that curl doesn't work, try to see if curl gives output for these links.

**Comment by mitchcapper** [comment]
I wrote a comment yesterday but for some reason didn't submit:
NVM I am an idiot. You mention hgrep I assumed https://github.com/rhysd/hgrep :)  Only once I started fixing the regexs and thought why would they use a syntax highlighter for all these.  I then rechecked and notice your hgrep was not what I had installed:)  Works just fine.
