### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by zooool** [TUVIMEN/xenforo-scraper#8]
I've installed this program and installed and "made" hgrep and jq, but when I execute `xenforo https://relevant.url` absolutely nothing happens. No download, no error, nothing. Are there any logs I can present to help debug?

**Comment by TUVIMEN** [comment]
If you are trying to start downloading the main page `xenforo --category https://relevant.url`, if this does not work try downloading some threads like `xenforo --thread https://relevant.url/threads/some-thing.4214/`. And if nothing from the above works try to use `curl https://relevant.url` and check if the output matches what your browser displays, there exists a chance that access is being blocked by cloudflare or something.
